### ISSUE TITLE
queryParameters

### ISSUE THREAD

**Issue by franckyinuk** [RSC-IoT/aws-sign-requests#1]
Hi,

Thanks for this module.
It is doing a good job with the signing.

One question though, how do you use the awsSignRequest with query parameters?
I have tried to add a qs in the request but my servers doesn't receive any. It looks like they are getting stipped out.

Here is what I am doing
  let config = new AWS.Config();
  let credentials = config.credentials;

  let options = awsSignRequests({
    credentials: {
        access_key: credentials.accessKeyId,
        secret_key: credentials.secretAccessKey,
        //session_token: credentials.session_token,
    },
    method: method,
    url: apiGateway,
    // headers: {'Content-Type': 'application/json'},
    // body: {name: "John Smith"},
    qs : queryParameters,
  });

  g_request(options, function (error : any, response : any, body: any){
     ...});

**Comment by jveldboom-rsc** [comment]
Glad to hear you're finding the module useful!

It was designed to work with a handful of different HTTP request libraries (like fetch, request) so it does not use the `qs` option commonly used in the request library. It actually only passes the following parameters in the be signed: method, url, headers, body.

To add a query string to the request, try adding it to the url. Would look something like this:

```javascript
let options = awsSignRequests({
  credentials: {
    access_key: credentials.accessKeyId,
    secret_key: credentials.secretAccessKey
  },
  method: method,
  url: `${apiGateway}?id=123`
});
```

**Comment by franckyinuk** [comment]
Thanks for the quick answer.
I tried many things today, and I think I did try that and I got an error message about the authentication signature not matching.
In the end I tried adding my parameters inside the request body and that worked.

**Comment by franckyinuk** [comment]
Hi,
I have found the issue I had. As a query like this wasn't working 
`?filename=name&content=someContent`
Inside canonical_request, the query parameter string is used as it comes (url_info.query).
As per AWS documentation, those parameters need to be sorted and encoded.
Once I used that then the signing was working for me with parameters.

Here is what I have used:
```
var canonical_query_string = function(qs){
    let cleanedParametersAndValues = [];
    if (qs){
        let parametersAndValues = qs.split("&");
        parametersAndValues.sort().forEach(element => {
        let pair = element.split("=");
        cleanedParametersAndValues.push(encodeURI(pair[0]) + "="+ encodeURI(pair[1] || ""));
        });
    }
    return cleanedParametersAndValues.join("&");
}
```
